stages:
  - prepare
  - build
  - test

.prepare-deb:
  stage: prepare
  image: ubuntu:16.04
  tags: 
   - deb 
   - docker
  only: 
   - /^PGPRO.*9_[56]$/
  before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export CORES=$(grep -c ^processor /proc/cpuinfo)
  - uname -a
  - df -h
  script:
    - echo "Current user id is `id`"
    - apt-get update && apt-get install -y sudo gcc make flex bison libreadline-dev zlib1g-dev openjade libzstd-dev opensp docbook docbook-xml docbook-xsl libxml2-utils xsltproc python-dev libicu-dev
    - id -u postgres || adduser --disabled-login --gecos "Postgres"  postgres
# Template build
.build_unix: &build_unix_def
  stage: build
  tags:
    - unix
  only:
    - /^PGPRO.*9_[56]$/
  script: 
    - .ci/build_and_test_world
  when: always

build_docs_job:
  stage: build
  when: always
  only: 
    - /^PGPRO.*9_[56]$/
  tags: 
    - docs
  script: 
    - ./configure
    - make -C doc

# Here definitions of particular build enviroments start

build_debian_8:
    <<: build_unix_def
    tags:
      - jessie
      - 64bit

build_debian_7_32:
    <<: build_unix_def
    tags:
      - wheezy
      - 32bit

