image: debian

stages:
  - test

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export CORES=$(grep -c ^processor /proc/cpuinfo)
  - uname -a
  - df -h

test:ubuntu-16.04:
  stage: test
  image: ubuntu:16.04
  only:
    - PGPROEE9_6
  before_script:
  	- echo "Current user id is `id`"
    - apt-get update && apt-get install -y sudo gcc make flex bison libreadline-dev zlib1g-dev openjade libzstd-dev opensp docbook docbook-xml docbook-xsl libxml2-utils xsltproc python-dev libicu-dev
  script:
    - ./configure --prefix=/opt/pgproee  --with-zstd --with-icu --with-python
    - make -j $CORES world
    - make check-world
  after_script:
  	- cat src/test/regress/log/initdb.log
  when: always
