language: c
os:
  - linux
  #- osx
compiler:
  #- gcc
  - clang
before_script: ./configure --enable-tap-tests && make -j4
env:
  - TESTDIR=.
  - TESTDIR=contrib/mmts
script: cd $TESTDIR && make check

