sudo: required

services:
  - docker

before_script: env && pip3 install -r contrib/mmts/tests2/requirements.txt

script: cd contrib/mmts/tests2 && python3 -m unittest discover

notifications:
  email:
    - s.kelvich@postgrespro.ru
    - k.knizhnik@postgrespro.ru

## Old TAP-based tests:

# language: perl
# os:
#   - linux
# compiler:
#   - gcc
#   - clang
# install: cpanm IPC::Run DBD::Pg Proc::ProcessTable
# before_script: ./configure --enable-cassert --enable-tap-tests && make -j4
# env:
#   - TESTDIR=contrib/raftable
#   - TESTDIR=contrib/mmts
# script: cd $TESTDIR && make check
# notifications:
#   email:
#     - s.kelvich@postgrespro.ru
#     - c.pan@postgrespro.ru
#     - k.knizhnik@postgrespro.ru
