language: perl
os:
  - linux
  #- osx
compiler:
  #- gcc
  - clang
install: cpanm IPC::Run DBD::Pg
before_script: ./configure --enable-tap-tests && make -j4
env:
  - TESTDIR=.
  - TESTDIR=src/test/recovery
  - TESTDIR=contrib/mmts
script: cd $TESTDIR && make check

