version: '2'

services:

  node1:
    container_name: node1
    build: ../..
    privileged: true
    ulimits:
      core: 14294967296
    environment:
      POSTGRES_USER: 'pg'
      POSTGRES_DB: 'regression'
      NODE_ID: 1
      MAJOR: 'off'
      CONNSTRS: >-
        dbname=regression user=pg host=node1,
        dbname=regression user=pg host=node2
    ports:
      - "15432:5432"

  node2:
    container_name: node2
    build: ../..
    privileged: true
    ulimits:
      core: 14294967296
    environment:
      POSTGRES_USER: 'pg'
      POSTGRES_DB: 'regression'
      NODE_ID: 2
      MAJOR: 'off'
      CONNSTRS: >-
        dbname=regression user=pg host=node1,
        dbname=regression user=pg host=node2
    ports:
      - "15433:5432"
