---

- hosts: all

  roles:
  - role: postgres
    pg_port: 5432
    pg_repo: https://github.com/postgrespro/postgres_cluster.git
    pg_version_tag: master
    pg_destroy_and_init: true

  tasks:
  - name: build raftable
    shell: "make clean && make -j {{makejobs}} install"
    args:
      chdir: "{{pg_src}}/contrib/raftable"

  - name: build multimaster
    shell: "make clean && make -j {{makejobs}} install"
    args:
      chdir: "{{pg_src}}/contrib/mmts"

