---

- hosts: all

  roles:
  - role: kelvich.postgres
    pg_port: 5432
    pg_repo: https://github.com/postgrespro/postgres_cluster.git
    pg_version_tag: master
    pg_destroy_and_init: true
    pg_config_role:
    - line: "multimaster.buffer_size = 65536"

  tasks:
  - name: generate connstrings
    set_fact:
      connstr: "host={{item}} user={{ansible_ssh_user}} dbname=postgres"
    with_items:
      groups['all'] | reverse | batch(nnodes | d(3) | int) | first
    register: connstrs

  - name: make a list
    set_fact:
      connections: "{{ connstrs.results | map(attribute='ansible_facts.connstr') | join(', ') }}"

  - debug: var=hostvars

  - debug: var=inventory_hostname

  #- debug: var=hostvars[inventory_hostname]

  - name: build raftable
    shell: "make clean && make -j {{makejobs}} install"
    args:
      chdir: "{{pg_src}}/contrib/raftable"

  - name: build multimaster
    shell: "make clean && make -j {{makejobs}} install"
    args:
      chdir: "{{pg_src}}/contrib/mmts"

  - name: enable dtm extension on datanodes
    lineinfile:
      dest: "{{pg_datadir}}/postgresql.conf"
      line: "{{item}}"
      state: present
    with_items:
    - "wal_level = logical"
    - "max_wal_senders = 10"
    - "wal_sender_timeout = 0"
    - "max_replication_slots = 10"
    - "max_connections = 200"
    - "max_worker_processes = 100"
    - "shared_preload_libraries = 'raftable,multimaster'"
    - "multimaster.conn_strings = '{{connections}}'"
    - "multimaster.node_id = {{ inventory_hostname | regex_replace('([0-9]+)', '\\1') }}"
    - "multimaster.buffer_size = 65536"
    - "multimaster.queue_size = 1073741824"
    - "multimaster.arbiter_port = 5600"
    - "multimaster.vacuum_delay = 1"
    - "multimaster.workers = 32"
    - "multimaster.use_dtm = 1"

  - name: restart postgrespro
    command: "{{pg_dst}}/bin/pg_ctl restart -w -D {{pg_datadir}} -l {{pg_datadir}}/pg.log"
    environment:
      LD_LIBRARY_PATH: "{{pg_dst}}/lib/"

